module.exports = {
  media: ["mp4", "mkv", "mp3"],
  archives: ["zip", "7z", "rar", "tar", "gz", "ar", "iso", "xz"],
  documents: [
    "docx",
    "doc",
    "pdf",
    "xlsx",
    "xls",
    "odt",
    "ods",
    "odp",
    "odg",
    "odf",
    "txt",
    "ps",
    "tex",
    "pptx",
    "txt",
  ],
  app: ["exe", "dmg", "pkg", "deb"],
  photo: ["jpg", "jpeg", "png"],
};
